#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# Zsh
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

# kitty
rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

# Tmux
rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# Git
ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig
ln -sf $DOTFILES/git/gitignore_global $HOME/.gitignore_global
ln -sf $DOTFILES/git/gitconfig.extra $HOME/.gitconfig.extra

mkdir -p $HOME/.local/bin

rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

rm -rf $HOME/.local/bin/login.sh
ln -s $DOTFILES/scripts/login.sh $HOME/.local/bin/login.sh

# Nvim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# phpactor
rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor

# NVM (Node Version Manager)
mkdir -p $HOME/.nvm
ln -sf $DOTFILES/nvm/default-packages $HOME/.nvm/default-packages

# LazyGit
rm -rf $HOME/.config/lazygit
ln -s $DOTFILES/lazygit $HOME/.config/lazygit

# Qutebrowser
rm -rf $HOME/.config/qutebrowser
ln -s $DOTFILES/qutebrowser $HOME/.config/qutebrowser

# Ranger
rm -rf $HOME/.config/ranger
ln -s $DOTFILES/ranger $HOME/.config/ranger

# Oh My Zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
